DROP TABLE IF EXISTS user;
-- DROP TABLE IF EXISTS post;
DROP TABLE IF EXISTS market;
DROP TABLE IF EXISTS uid_mid;
DROP TABLE IF EXISTS imgs;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL
);

CREATE TABLE market (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  market_name TEXT NOT NULL,
  -- user_ids 
  lat REAL,
  long REAL
);

CREATE TABLE uid_mid (
  user_id INTEGER PRIMARY KEY,
  market_id INTEGER
);

CREATE TABLE imgs (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  img_data BLOB
)

-- CREATE TABLE post (
--   id INTEGER PRIMARY KEY AUTOINCREMENT,
--   author_id INTEGER NOT NULL,
--   created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
--   title TEXT NOT NULL,
--   body TEXT NOT NULL,
--   FOREIGN KEY (author_id) REFERENCES user (id)
-- );

